# Generated by Django 4.0.1 on 2022-02-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('primary_id', models.AutoField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
