# Generated by Django 4.0.1 on 2022-02-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arisencode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='primary_id',
        ),
        migrations.AddField(
            model_name='list',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
